$(function(){
	$(".sousuo").click(function(){
		$(".back").siblings().hide();
		$(".text").show();
		$(".cancel").show().css({
			display:"inline-block",
			width:"10%",
			height:"28px",
			lineHeight:"28px",
			textAlign:"center"
		});
		$(".cancel").click(function(){
			$(".text").val("");
		})
	});
});
    var app=angular.module("myApp",[]);
	app.controller("main",function($scope,$http){
		console.log(1);
        $http.get("C:/Users/蓝科教育/Documents/GitHub/Adorable-pet-house/json/data.json").success(function(res){
            console.log(res);
            $scope.data=res.data;
        })
	})